### ISSUE TITLE
Overly aggressive vectorization of * in chebop

### ISSUE THREAD

**Issue by tobydriscoll** [chebfun/chebfun.github.io#15]
Sometimes a * really should be a * and not a .*. For example:
```
N = chebop(0,1);
V = operatorBlock.volt(@(x,t) exp(t.*(x-t)),[0,1]);
N.op = @(x,y) diff(y) + y - x.*(1+2*x).*(V*y)-1-2*x;
```
The result is stored incorrectly as
```
>> N.op

ans =

  function_handle with value:

    @(x,y)diff(y)+y-x.*(1+2.*x).*(V.*y)-1-2.*x
```
which throws an error for the Volterra block when using the chebop.

**Comment by trefethen** [comment]
@tobydriscoll, you are closer to this than the rest of us -- is there a particular suggestion you would like to make about what we should do?

Unrelatedly -- did you mean for this issue to be put in a different tracker?

**Comment by nickhale** [comment]
Is this really the syntax we expect users to use? (I hope not!)

In any case, now that '.*' is not required at the `chebfun` level, does this vectorisation need to take place here at all?

**Comment by tobydriscoll** [comment]
Sorry for the wrong tracker. I'll move it there.
