### ISSUE TITLE
Can't view GitHub file of examples

### ISSUE THREAD

**Issue by NBoulle** [chebfun/chebfun.github.io#17]
If I open this example:
https://www.chebfun.org/examples/linalg/NonsmoothFOV.html
and click on `view on GitHub`, I'm redirected to this webpage:
https://github.com/chebfun/examples/tree/development/linalg/NonsmoothFOV.m,
which doesn't work because the development branch has been deleted.
It should instead be
https://github.com/chebfun/examples/tree/master/linalg/NonsmoothFOV.m

**Comment by NBoulle** [comment]
This commit might solve the issue:
https://github.com/rothos/chebsite/pull/2/commits/77d5089be4db5a332ae2cba77dee089ddea1c067

**Comment by abigopal** [comment]
solved by  6bd8dd2
